# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 2.7
    - python: pypy
    - python: 3.7
      dist: xenial

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install pytest -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test
